dist: bionic
language: ruby
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
before_install:
  - gem install bundler
  - sudo apt-get install libzmq3-dev
before_script:
  - "bundle exec appraisal install"
script: "bundle exec appraisal rake test integration"
